# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: Lee Cannon <leecannon@leecannon.xyz>

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
