# SPDX-License-Identifier: LicenseRef-NON-AI-CC0-1.0
# SPDX-FileCopyrightText: CascadeOS Contributors

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
