# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: CascadeOS Contributors

version = 1
SPDX-PackageName = "CascadeOS"
SPDX-PackageSupplier = "CascadeOS Contributors"
SPDX-PackageDownloadLocation = "https://github.com/CascadeOS/CascadeOS"

[[annotations]]
path = "**.md"
precedence = "aggregate"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "CascadeOS Contributors"

[[annotations]]
path = ".assets/justforfunnoreally_dev.svg"
precedence = "aggregate"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "https://shields.io/>"

[[annotations]]
path = ".assets/no_ai.svg"
precedence = "aggregate"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "https://shields.io/"

[[annotations]]
path = "kernel/cascade/init/output/simple.font"
precedence = "aggregate"
SPDX-License-Identifier = "OFL-1.1"
SPDX-FileCopyrightText = ""

[[annotations]]
path = ".keys/**"
precedence = "aggregate"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "CascadeOS Contributors"
