# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2024 Lee Cannon <leecannon@leecannon.xyz>

FROM mcr.microsoft.com/devcontainers/base:ubuntu-22.04
RUN apt update
RUN apt upgrade -y
RUN apt install -y qemu-system-arm qemu-system-x86 qemu-kvm qemu-user
