# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2024 Lee Cannon <leecannon@leecannon.xyz>

name: CI

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/CI.yml"
      - "**.zig"
      - "**.zig.zon"
  pull_request:
    paths:
      - ".github/workflows/CI.yml"
      - "**.zig"
      - "**.zig.zon"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Grab zig
        uses: mlugg/setup-zig@v1
        with:
          version: master

      - name: Lint
        run: zig fmt --check --ast-check **.zig

      - name: Test
        run: zig build test --summary all
