# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: Lee Cannon <leecannon@leecannon.xyz>

name: CI

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/CI.yml"
      - "**.zig"
      - "**.zig.zon"
      - "**.c"
      - "**.h"
  pull_request:
    paths:
      - ".github/workflows/CI.yml"
      - "**.zig"
      - "**.zig.zon"
      - "**.c"
      - "**.h"
  workflow_dispatch:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Grab zig
        # FIXME: once https://github.com/mlugg/setup-zig/pull/30 is in a released version switch to that
        uses: mlugg/setup-zig@915f70607f6642da2dd36333035f4221a7bc8618

      - name: Lint
        run: zig fmt --check --ast-check .

      - name: Test
        run: zig build test --summary all
