name: CI

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/CI.yml"
      - "**.zig"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/CI.yml"
      - "**.zig"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Grab zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - name: Cache
        uses: Hanaasagi/zig-action-cache@master

      - name: Lint
        run: zig fmt --check --ast-check **.zig

      - name: Test
        run: zig build test --summary all
